if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall
endif

" Use Vim settings, instead of Vi.
set nocompatible
filetype on
set ff=unix
set relativenumber
set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab

inoremap jk <Esc>
let mapleader = ","
nnoremap <leader>w <C-w>

nnoremap <leader>ev :vsplit $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>
" Toggle paste mode
set pastetoggle=<F10>

function! LanguageConfig(filename)
  let l:filename = "lang_config/" . a:filename . ".vim"
  exec "runtime " . l:filename
endfunction

function! PluginConfig(filename)
  let l:filename = "plugin_config/" . a:filename . ".vim"
  exec "runtime " . l:filename
endfunction

let &runtimepath .= ",$HOME/Code/dotfiles/vim"

source $HOME/.vim/autoload/plug.vim

"Solarized theme
source $HOME/Code/dotfiles/vim/colors/config.vim

augroup vimrcEx
  autocmd!

"Plugin Configuration
call PluginConfig("vim-plug")
call PluginConfig("syntastic")
call PluginConfig("ycm")
call PluginConfig("ctrlp")
call PluginConfig("ultisnips")
call PluginConfig("vim-commentary")
call PluginConfig("phpcomplete-extended")
call PluginConfig("nerdtree")
" Add in A.vim for switching between .h and .c files

augroup END
" Language Configuration

colorscheme solarized
