#!/bin/bash 

if [ $(uname) == 'Darwin' ]; then
    echo 'Please install pbcopy'
    exit 0
fi

xclipPath=$(which xclip)
if [ -x "$xclipPath" ]; then
    cat | xclip -selection c
    exit 0
fi

cat | nc -q1 localhost 2224
