#!/bin/bash 

if [ -z "$SSH_AUTH_SOCK" ]; then

    if [ $(uname) == 'Darwin' ]; then
        if [ -x $(which pbcopy) ]; then
            cat | pbcopy
            exit 0
        else
            echo 'Please install pbcopy'
            exit 1
        fi
    fi

    xclipPath=$(which xclip)
    if [ -x "$xclipPath" ]; then
        cat | xclip -selection c
        exit 0
    fi
else
    cat | nc -q1 localhost 2224
fi
