# Below is the PATH used before trying to fix vim and python issues
#export PATH=/usr/local/php5/bin:$PATH":vendor/bin:~/.composer/vendor/bin"
export PATH=/usr/local/bin:$PATH":vendor/bin:~/.composer/vendor/bin"

source ~/.bashrc #get alias

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

export JTAGCONFIG=interface/jtagkey-tiny.cfg
alias sshconfigv='vim ~/.ssh/config'
