if [ -x "$(command -v nvim)" ]; then
    # If neovim exists alias it to vim
    echo 'Using neovim'
    alias vim='nvim'
fi

alias vimrc='vim ~/.vimrc'

#vagrant
alias vaprobash='curl -L http://bit.ly/vaprobash > Vagrantfile'

#reload bash configuration
alias reload='source ~/.bash_profile'

#phpunit
alias t='vendor/bin/phpunit tests/'
alias unit='vendor/bin/phpunit'
alias td='vendor/bin/phpunit --debug app/tests' 
alias nw='vendor/phpunit/phpunit/phpunit'

#behat
alias be='vendor/bin/behat'

#git
alias ga="git add"
alias gaa="git add ."
alias gs='git status'
alias gp='git push'
alias gpo='git push origin'
alias gpom='git push origin master'

#codeception
alias code:api='php artisan migrate:refresh --env=codeception && codecept run api'

#gymbro ssh
alias gymbro='ssh -p 21098 gymbkqat@162.213.253.12'

#laravel
alias art='php artisan'
alias g:m='php artisan generate:migration'
alias d:seed='php artisan db:seed'
alias g:c='php artisan generate:controller'
alias g:mo='php artisan generate:model'
alias g:seed='php artisan generate:seed'
alias command:g='php artisan commander:generate'

#homestead
alias homestead='~/.composer/vendor/laravel/homestead/homestead'

#gradle
alias grun='./gradlew run'
alias gtest='./gralew test'

#SSH Ubuntu
alias ubuntu='ssh 98.239.240.211'

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

# nowait 
alias nw-phpmig="../../bin/phpmig"
alias nw-exec="docker exec -it nowait-server"

alias cs-exec="docker exec -it checkstatus"

# docker
alias dc="docker-compose"
alias dm="docker-machine"

# cheat
export CHEATCOLORS=true

#tmux
alias tmux="TERM=screen-256color-bce tmux -2"

#grep
alias grep="grep --exclude-dir={node_modules,vendor,.git}"

# nvm / npm stuff
export NPM_TOKEN="29b91150-5ec8-440a-9e9a-389c5939b20f"
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm
