# Below is the PATH used before trying to fix vim and python issues
#export PATH=/usr/local/php5/bin:$PATH":vendor/bin:~/.composer/vendor/bin"
export PATH=/usr/local/bin:$PATH":vendor/bin:~/.composer/vendor/bin"

# TODO: Detect the operating system here and set the path
# accordingly
# OSX /Users/$USER/dotfiles/bash/bashrc
# Linux /home/$USER/dotfiles/bash/bashrc
source /home/$USER/Code/dotfiles/bash/bashrc #get alias

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

export JTAGCONFIG=interface/jtagkey-tiny.cfg
alias sshconfigv='vim ~/.ssh/config'
